version: '3.8'

services:
  backend:
    image: busbus61/student-registration:latest
    # build: 
    #   context: /home/buse/student-registration
    #   dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/student_db
    ports:
      - "8090:8090"
    networks:
      - app-network
    depends_on:
      - postgres
    command: >
      sh -c "sleep 30 && java -jar /student-registration.jar"

  frontend:
    #image: busbus61/vite-project:latest
    build: 
      context: /home/buse/vite-project
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    networks:
      - app-network
    depends_on:
      - backend

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=busbus
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=student_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
